### ISSUE TITLE
Ionic 3 compatible?

### ISSUE THREAD

**Issue by julioaze** [subarroca/ng-gauge#10]
Hi,
This gauge project is compatible with Ionic 3 projects?

Regards

**Comment by eduibrahim** [comment]
Any answer?

**Comment by vicatcu** [comment]
@eduibrahim I have used this in an Ionic3 project. Not sure if that's what you mean by "compatible" though. I put the code in [this folder](https://github.com/subarroca/ng-gauge/tree/master/src/app/gauge) into a vendor subdirectory under my project's src folder, then in my app.module.ts I did:

```javascript
 import { GaugeModule } from '../vendor/gauge';
...
@NgModule({
   ...
  imports: [
     ... 
     GaugeModule
```
